// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBgoY8Sghi0SuIegeFLOKvyQ1V7o0lQb5o',
    appId: '1:653361484618:web:001a64b236b4f0460da7b3',
    messagingSenderId: '653361484618',
    projectId: 'smart-task-manager-f9e1e',
    authDomain: 'smart-task-manager-f9e1e.firebaseapp.com',
    storageBucket: 'smart-task-manager-f9e1e.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDhPco4da1ZuhnU4H5zzTlMCTs0I-9unlU',
    appId: '1:653361484618:android:cb9dd7819e3fb68f0da7b3',
    messagingSenderId: '653361484618',
    projectId: 'smart-task-manager-f9e1e',
    storageBucket: 'smart-task-manager-f9e1e.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDmCcij0goc3bORZppWnxWoGA62PxCIr_Q',
    appId: '1:653361484618:ios:aa3b6b3ad94f625e0da7b3',
    messagingSenderId: '653361484618',
    projectId: 'smart-task-manager-f9e1e',
    storageBucket: 'smart-task-manager-f9e1e.firebasestorage.app',
    iosBundleId: 'com.example.smartTaskManager',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDmCcij0goc3bORZppWnxWoGA62PxCIr_Q',
    appId: '1:653361484618:ios:aa3b6b3ad94f625e0da7b3',
    messagingSenderId: '653361484618',
    projectId: 'smart-task-manager-f9e1e',
    storageBucket: 'smart-task-manager-f9e1e.firebasestorage.app',
    iosBundleId: 'com.example.smartTaskManager',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBgoY8Sghi0SuIegeFLOKvyQ1V7o0lQb5o',
    appId: '1:653361484618:web:f5cdbf5acf0736e20da7b3',
    messagingSenderId: '653361484618',
    projectId: 'smart-task-manager-f9e1e',
    authDomain: 'smart-task-manager-f9e1e.firebaseapp.com',
    storageBucket: 'smart-task-manager-f9e1e.firebasestorage.app',
  );
}
